version: "3.6"
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./app:/app
    env_file:
      - .env
    command: /start-reload.sh
    environment:
      - PORT=8888
